sudo: required
services:
  - docker
language: c
script: bash -ex ./.docker-run.sh
env:
  global:
  - OCAML_VERSIONS="4.04.2 4.05.0 4.06.0"
  matrix:
  - DISTRO="debian-9"
  - DISTRO="alpine-3.6"
  - DISTRO="ubuntu-16.04"
